### PR TITLE
Merge patches from @macrat for additional syntax support

### PR DESCRIPTION
**Pull request by jrabinow**
https://github.com/macrat/sphinxcontrib-golangdomain/commits/master added a couple commits to support a few extra syntax cases, I think it would be worthwhile merging them in here as well.

Additionally, I reformatted the code using python-black

To see just the code changes, you can check the last commit (the merge). Apologies, I should have made 2 PRs, one for formatting and the other for the updated syntax. If you would prefer we take that route, please let me know

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
Looking good. How did you test?

**Comment by jrabinow** [comment]
I'm still struggling to get this thing up and running with sphinx3, @macrat created a test in the "supported interface{} in the function definition" commit. Hopefully he can answer about the grammar changes, if not, I will get back to you once I'm done getting this to work (heads up, it may take a while)

**Comment by chrisdoherty4** [comment]
No bother. I meant to put a CI together a while back but never got round to it and consequently forgot. Will try and sort something soon.

**Comment by macrat** [comment]
Thanks for using my commits.

There are no enough test samples because those commits were what I thought just for me.

Maybe adding tests to test/index.rst is not difficult.
But, if you set up a CI test (I think it is very good), I think adding to the CI is better.

Please tell me if there is anything I can help.

**Comment by jrabinow** [comment]
Oh wow, that would be awesome having CI for this package. It looks like I've run into a couple edge cases while trying to integrate with my project - (I'm brand new to sphinx-autoapi, so odds are I'm messing something up). I'll keep you posted once I have things figured out.

@macrat if you have a code sample that specifically tests [this commit](https://github.com/chrisdoherty4/sphinxcontrib-golangdomain/pull/1/commits/38130e9d5cfdb2f1404027921c6afdf249d2f186), I believe that would be quite helpful. If you don't have, no worries, I'll try to get to it sometime. Either way, thank you for writing those commits!

**Comment by macrat** [comment]
38130e9d5cfdb2f1404027921c6afdf249d2f186 is a commit for accept `{}` to argument or return value type.

You can test it by code like below.

``` rest
.. go:function:: func Function(a interface{}, b struct{C int}) []interface{}
```

**Pull request merged**
